@baseUrl = http://localhost:3002
@token = bearer_token_aqui

### Registrar Devolução de Livro - Sucesso
PUT {{baseUrl}}/loans/1/return
Authorization: Bearer {{token}}

### Registrar Devolução de Livro - Erro 404 (Empréstimo não encontrado)
PUT {{baseUrl}}/loans/999/return
Authorization: Bearer {{token}}

### Registrar Devolução de Livro - Erro 403 (Usuário não é dono do livro)
PUT {{baseUrl}}/loans/2/return
Authorization: Bearer {{token}}
