@baseUrl = http://localhost:3002
@token = 11111111-1111-1111-1111-111111111111

### Registrar Devolução de Livro - Sucesso
PUT {{baseUrl}}/loans/11111111-1111-1111-1111-111111111111/return
Authorization: Bearer {{token}}

### Registrar Devolução de Livro - Erro 404 (Empréstimo não encontrado)
PUT {{baseUrl}}/loans/99999999-9999-9999-9999-999999999999/return
Authorization: Bearer {{token}}

### Registrar Devolução de Livro - Erro 403 (Usuário não é dono do livro)
PUT {{baseUrl}}/loans/22222222-2222-2222-2222-222222222222/return
Authorization: Bearer {{token}}
