version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bookshare-postgres
    restart: always
    environment:
      POSTGRES_USER: mrn
      POSTGRES_PASSWORD: Ping2012
      POSTGRES_DB: bookshare_db
    ports:
      - "5433:5432"
    volumes:
      - bookshare_pg_data:/var/lib/postgresql/data
    networks:
      - bookshare_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookshare-app
    restart: always
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=mrn
      - DB_PASSWORD=Ping2012
      - DB_DATABASE=bookshare_db
      - PORT=3002
    depends_on:
      - db
    networks:
      - bookshare_network

volumes:
  bookshare_pg_data:

networks:
  bookshare_network:
    driver: bridge